USE operational_db;

CREATE TABLE IF NOT EXISTS customers (
    id         INT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    country    VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id         INT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    group_name VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    customer_id INT NOT NULL,
    product_id  INT NOT NULL,
    qty         INT NOT NULL,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);