INSERT INTO customers (id, name, country, updated_at) VALUES (1, 'Reuven Cresswell', 'Portugal', '2024-04-15');
INSERT INTO customers (id, name, country, updated_at) VALUES (2, 'Concordia Vuitte', 'Greece', '2024-02-28');
INSERT INTO customers (id, name, country, updated_at) VALUES (3, 'Nikolas Widger', 'Portugal', '2024-05-14');
INSERT INTO customers (id, name, country, updated_at) VALUES (4, 'Stanislaw Bernier', 'United Kingdom', '2024-04-15');
INSERT INTO customers (id, name, country, updated_at) VALUES (5, 'Shelton Kubasiewicz', 'Portugal', '2024-07-11');
INSERT INTO customers (id, name, country, updated_at) VALUES (6, 'Sasha Nunnery', 'Portugal', '2024-10-08');
INSERT INTO customers (id, name, country, updated_at) VALUES (7, 'Lennie McEwan', 'Portugal', '2024-12-29');
INSERT INTO customers (id, name, country, updated_at) VALUES (8, 'Silvio Hulstrom', 'Greece', '2024-03-10');
INSERT INTO customers (id, name, country, updated_at) VALUES (9, 'Gilburt Thornhill', 'Greece', '2024-08-13');
INSERT INTO customers (id, name, country, updated_at) VALUES (10, 'Anstice Ambrois', 'France', '2024-10-27');
INSERT INTO customers (id, name, country, updated_at) VALUES (11, 'Wakefield Keigher', 'France', '2024-02-07');
INSERT INTO customers (id, name, country, updated_at) VALUES (12, 'Venus Lufkin', 'Portugal', '2024-04-28');
INSERT INTO customers (id, name, country, updated_at) VALUES (13, 'Tasia De Meis', 'Portugal', '2024-07-25');
INSERT INTO customers (id, name, country, updated_at) VALUES (14, 'Nils McTurk', 'Portugal', '2024-10-08');
INSERT INTO customers (id, name, country, updated_at) VALUES (15, 'Ragnar Jedrychowski', 'Portugal', '2024-04-23');
INSERT INTO customers (id, name, country, updated_at) VALUES (16, 'Mike Camois', 'Greece', '2024-07-15');
INSERT INTO customers (id, name, country, updated_at) VALUES (17, 'Winny Swynfen', 'Portugal', '2024-12-17');
INSERT INTO customers (id, name, country, updated_at) VALUES (18, 'Yulma Coate', 'France', '2024-09-22');
INSERT INTO customers (id, name, country, updated_at) VALUES (19, 'Cristy Stadden', 'Portugal', '2024-06-21');
INSERT INTO customers (id, name, country, updated_at) VALUES (20, 'Tanny Lawrinson', 'France', '2024-11-01');
INSERT INTO customers (id, name, country, updated_at) VALUES (21, 'Thomasina Doerren', 'Portugal', '2024-09-11');
INSERT INTO customers (id, name, country, updated_at) VALUES (22, 'Terza Brotherhood', 'France', '2024-12-16');
INSERT INTO customers (id, name, country, updated_at) VALUES (23, 'Elna Fausset', 'Portugal', '2024-11-09');
INSERT INTO customers (id, name, country, updated_at) VALUES (24, 'Leslie Badam', 'Germany', '2024-10-20');
INSERT INTO customers (id, name, country, updated_at) VALUES (25, 'May Denzilow', 'United Kingdom', '2024-07-19');
INSERT INTO customers (id, name, country, updated_at) VALUES (26, 'Yule Wabersinke', 'Portugal', '2024-10-16');
INSERT INTO customers (id, name, country, updated_at) VALUES (27, 'Bethena Frounks', 'Portugal', '2024-06-28');
INSERT INTO customers (id, name, country, updated_at) VALUES (28, 'Ellie Henrionot', 'France', '2024-11-20');
INSERT INTO customers (id, name, country, updated_at) VALUES (29, 'Claudina Sprade', 'Portugal', '2024-12-27');
INSERT INTO customers (id, name, country, updated_at) VALUES (30, 'Durant Breckwell', 'Spain', '2024-10-29');
INSERT INTO customers (id, name, country, updated_at) VALUES (31, 'Tatiania Wasielewicz', 'France', '2024-04-04');
INSERT INTO customers (id, name, country, updated_at) VALUES (32, 'Jere Eccleston', 'France', '2024-11-10');
INSERT INTO customers (id, name, country, updated_at) VALUES (33, 'Lissa Thomton', 'Portugal', '2024-03-24');
INSERT INTO customers (id, name, country, updated_at) VALUES (34, 'Britney Catteroll', 'France', '2024-02-04');
INSERT INTO customers (id, name, country, updated_at) VALUES (35, 'Dorette Dornin', 'Portugal', '2024-11-26');
INSERT INTO customers (id, name, country, updated_at) VALUES (36, 'Llywellyn Sears', 'Portugal', '2024-03-29');
INSERT INTO customers (id, name, country, updated_at) VALUES (37, 'Kimmie Mattioni', 'Portugal', '2024-09-06');
INSERT INTO customers (id, name, country, updated_at) VALUES (38, 'Jereme Barten', 'France', '2024-06-20');
INSERT INTO customers (id, name, country, updated_at) VALUES (39, 'Tore Jacquet', 'Portugal', '2024-10-05');
INSERT INTO customers (id, name, country, updated_at) VALUES (40, 'Emlyn De Maria', 'Greece', '2024-08-24');
INSERT INTO customers (id, name, country, updated_at) VALUES (41, 'Cristian Wohler', 'Netherlands', '2024-01-31');
INSERT INTO customers (id, name, country, updated_at) VALUES (42, 'Duff Elvy', 'Spain', '2024-12-05');
INSERT INTO customers (id, name, country, updated_at) VALUES (43, 'Angeline Follos', 'France', '2024-08-20');
INSERT INTO customers (id, name, country, updated_at) VALUES (44, 'Nat Eglese', 'France', '2024-09-17');
INSERT INTO customers (id, name, country, updated_at) VALUES (45, 'Gamaliel Farrin', 'Portugal', '2024-05-16');
INSERT INTO customers (id, name, country, updated_at) VALUES (46, 'Dulcea Van Leeuwen', 'Portugal', '2024-11-01');
INSERT INTO customers (id, name, country, updated_at) VALUES (47, 'Maggy Anan', 'Portugal', '2024-01-25');
INSERT INTO customers (id, name, country, updated_at) VALUES (48, 'Caspar Ryce', 'France', '2024-11-22');
INSERT INTO customers (id, name, country, updated_at) VALUES (49, 'Lizzy Eveque', 'France', '2024-08-10');
INSERT INTO customers (id, name, country, updated_at) VALUES (50, 'Joscelin Longwood', 'Portugal', '2024-05-08');