INSERT INTO products (id, name, group_name, updated_at) VALUES (1, 'Classic Cotton T-Shirt', 'Tops', '2024-01-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (2, 'Slim Fit Jeans', 'Bottoms', '2024-01-20');
INSERT INTO products (id, name, group_name, updated_at) VALUES (3, 'Wool Cashmere Coat', 'Outerwear', '2024-10-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (4, 'Leather Ankle Boots', 'Footwear', '2024-09-12');
INSERT INTO products (id, name, group_name, updated_at) VALUES (5, 'Silk Evening Blouse', 'Tops', '2024-05-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (6, 'Cargo Pants', 'Bottoms', '2024-02-14');
INSERT INTO products (id, name, group_name, updated_at) VALUES (7, 'Down Puffer Jacket', 'Outerwear', '2024-11-01');
INSERT INTO products (id, name, group_name, updated_at) VALUES (8, 'Running Sneakers', 'Footwear', '2024-06-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (9, 'Cashmere Beanie', 'Accessories', '2024-12-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (10, 'Linen Button-Up Shirt', 'Tops', '2024-07-22');
INSERT INTO products (id, name, group_name, updated_at) VALUES (11, 'Pleated Wool Skirt', 'Bottoms', '2024-04-07');
INSERT INTO products (id, name, group_name, updated_at) VALUES (12, 'Leather Biker Jacket', 'Outerwear', '2024-10-30');
INSERT INTO products (id, name, group_name, updated_at) VALUES (13, 'High-Top Canvas Shoes', 'Footwear', '2024-08-03');
INSERT INTO products (id, name, group_name, updated_at) VALUES (14, 'Silk Scarf', 'Accessories', '2024-03-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (15, 'Merino Wool Sweater', 'Tops', '2024-01-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (16, 'Yoga Leggings', 'Bottoms', '2024-06-01');
INSERT INTO products (id, name, group_name, updated_at) VALUES (17, 'Trench Coat', 'Outerwear', '2024-09-19');
INSERT INTO products (id, name, group_name, updated_at) VALUES (18, 'Leather Loafers', 'Footwear', '2024-05-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (19, 'Leather Belt', 'Accessories', '2024-11-20');
INSERT INTO products (id, name, group_name, updated_at) VALUES (20, 'Hooded Sweatshirt', 'Tops', '2024-08-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (21, 'Denim Jacket', 'Outerwear', '2024-01-12');
INSERT INTO products (id, name, group_name, updated_at) VALUES (22, 'Flip Flops', 'Footwear', '2024-07-07');
INSERT INTO products (id, name, group_name, updated_at) VALUES (23, 'Wool Scarf', 'Accessories', '2024-12-01');
INSERT INTO products (id, name, group_name, updated_at) VALUES (24, 'Polo Shirt', 'Tops', '2024-02-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (25, 'Chino Shorts', 'Bottoms', '2024-06-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (26, 'Raincoat', 'Outerwear', '2024-04-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (27, 'Winter Boots', 'Footwear', '2024-11-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (28, 'Baseball Cap', 'Accessories', '2024-05-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (29, 'Oversized Hoodie', 'Tops', '2024-03-03');
INSERT INTO products (id, name, group_name, updated_at) VALUES (30, 'Corduroy Pants', 'Bottoms', '2024-10-22');
INSERT INTO products (id, name, group_name, updated_at) VALUES (31, 'Faux Fur Coat', 'Outerwear', '2024-12-20');
INSERT INTO products (id, name, group_name, updated_at) VALUES (32, 'Trail Running Shoes', 'Footwear', '2024-08-14');
INSERT INTO products (id, name, group_name, updated_at) VALUES (33, 'Knitted Gloves', 'Accessories', '2024-01-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (34, 'Turtleneck Sweater', 'Tops', '2024-09-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (35, 'Wide Leg Trousers', 'Bottoms', '2024-02-08');
INSERT INTO products (id, name, group_name, updated_at) VALUES (36, 'Bomber Jacket', 'Outerwear', '2024-07-30');
INSERT INTO products (id, name, group_name, updated_at) VALUES (37, 'Espadrilles', 'Footwear', '2024-06-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (38, 'Sunglasses', 'Accessories', '2024-03-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (39, 'Graphic Tee', 'Tops', '2024-04-12');
INSERT INTO products (id, name, group_name, updated_at) VALUES (40, 'Culottes', 'Bottoms', '2024-08-20');
INSERT INTO products (id, name, group_name, updated_at) VALUES (41, 'Parka', 'Outerwear', '2024-10-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (42, 'Hiking Boots', 'Footwear', '2024-05-22');
INSERT INTO products (id, name, group_name, updated_at) VALUES (43, 'Wristwatch', 'Accessories', '2024-07-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (44, 'Camisole Top', 'Tops', '2024-11-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (45, 'Paperbag Waist Pants', 'Bottoms', '2024-01-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (46, 'Varsity Jacket', 'Outerwear', '2024-09-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (47, 'Ballet Flats', 'Footwear', '2024-02-02');
INSERT INTO products (id, name, group_name, updated_at) VALUES (48, 'Hair Scrunchie', 'Accessories', '2024-05-12');
INSERT INTO products (id, name, group_name, updated_at) VALUES (49, 'Ribbed Tank Top', 'Tops', '2024-03-22');
INSERT INTO products (id, name, group_name, updated_at) VALUES (50, 'Jogger Pants', 'Bottoms', '2024-12-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (51, 'Peacoat', 'Outerwear', '2024-11-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (52, 'Sandals', 'Footwear', '2024-06-30');
INSERT INTO products (id, name, group_name, updated_at) VALUES (53, 'Fanny Pack', 'Accessories', '2024-04-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (54, 'Off-Shoulder Top', 'Tops', '2024-08-08');
INSERT INTO products (id, name, group_name, updated_at) VALUES (55, 'Leather Pants', 'Bottoms', '2024-10-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (56, 'Quilted Vest', 'Outerwear', '2024-01-08');
INSERT INTO products (id, name, group_name, updated_at) VALUES (57, 'Platform Sneakers', 'Footwear', '2024-09-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (58, 'Earrings', 'Accessories', '2024-07-02');
INSERT INTO products (id, name, group_name, updated_at) VALUES (59, 'Crop Top', 'Tops', '2024-05-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (60, 'Drawstring Shorts', 'Bottoms', '2024-03-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (61, 'Windbreaker', 'Outerwear', '2024-06-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (62, 'Mules', 'Footwear', '2024-11-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (63, 'Necklace', 'Accessories', '2024-02-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (64, 'Henley Shirt', 'Tops', '2024-04-02');
INSERT INTO products (id, name, group_name, updated_at) VALUES (65, 'Straight Leg Jeans', 'Bottoms', '2024-09-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (66, 'Shearling Jacket', 'Outerwear', '2024-12-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (67, 'Running Sandals', 'Footwear', '2024-07-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (68, 'Beanie Hat', 'Accessories', '2024-01-30');
INSERT INTO products (id, name, group_name, updated_at) VALUES (69, 'Muscle Tee', 'Tops', '2024-08-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (70, 'High Waist Jeans', 'Bottoms', '2024-10-01');
INSERT INTO products (id, name, group_name, updated_at) VALUES (71, 'Blazer', 'Outerwear', '2024-03-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (72, 'Slippers', 'Footwear', '2024-12-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (73, 'Backpack', 'Accessories', '2024-06-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (74, 'Peplum Top', 'Tops', '2024-02-20');
INSERT INTO products (id, name, group_name, updated_at) VALUES (75, 'Pleather Skirt', 'Bottoms', '2024-05-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (76, 'Leather Jacket', 'Outerwear', '2024-11-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (77, 'Oxford Shoes', 'Footwear', '2024-01-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (78, 'Tote Bag', 'Accessories', '2024-04-30');
INSERT INTO products (id, name, group_name, updated_at) VALUES (79, 'Racerback Tank', 'Tops', '2024-07-12');
INSERT INTO products (id, name, group_name, updated_at) VALUES (80, 'Flared Pants', 'Bottoms', '2024-09-02');
INSERT INTO products (id, name, group_name, updated_at) VALUES (81, 'Poncho', 'Outerwear', '2024-02-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (82, 'Wedges', 'Footwear', '2024-03-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (83, 'Gloves', 'Accessories', '2024-10-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (84, 'Button Down Shirt', 'Tops', '2024-04-22');
INSERT INTO products (id, name, group_name, updated_at) VALUES (85, 'Denim Shorts', 'Bottoms', '2024-08-12');
INSERT INTO products (id, name, group_name, updated_at) VALUES (86, 'Fleece Jacket', 'Outerwear', '2024-01-10');
INSERT INTO products (id, name, group_name, updated_at) VALUES (87, 'Snow Boots', 'Footwear', '2024-12-08');
INSERT INTO products (id, name, group_name, updated_at) VALUES (88, 'Headband', 'Accessories', '2024-05-02');
INSERT INTO products (id, name, group_name, updated_at) VALUES (89, 'Long Sleeve Tee', 'Tops', '2024-06-22');
INSERT INTO products (id, name, group_name, updated_at) VALUES (90, 'Knit Pants', 'Bottoms', '2024-03-08');
INSERT INTO products (id, name, group_name, updated_at) VALUES (91, 'Leather Vest', 'Outerwear', '2024-07-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (92, 'Casual Loafers', 'Footwear', '2024-09-25');
INSERT INTO products (id, name, group_name, updated_at) VALUES (93, 'Suspenders', 'Accessories', '2024-11-12');
INSERT INTO products (id, name, group_name, updated_at) VALUES (94, 'Flannel Shirt', 'Tops', '2024-02-05');
INSERT INTO products (id, name, group_name, updated_at) VALUES (95, 'Bermuda Shorts', 'Bottoms', '2024-06-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (96, 'Duffle Coat', 'Outerwear', '2024-10-15');
INSERT INTO products (id, name, group_name, updated_at) VALUES (97, 'Combat Boots', 'Footwear', '2024-04-08');
INSERT INTO products (id, name, group_name, updated_at) VALUES (98, 'Bow Tie', 'Accessories', '2024-07-28');
INSERT INTO products (id, name, group_name, updated_at) VALUES (99, 'Seamless Sports Bra', 'Tops', '2024-08-18');
INSERT INTO products (id, name, group_name, updated_at) VALUES (100, 'Track Pants', 'Bottoms', '2024-09-30');